### ISSUE TITLE
performance en toegankelijkheid test

### ISSUE THREAD

**Issue by J3SS3HVA** [SamaraFellaDina/future-ready-design#227]
page.speed.dev is een website van lighthouse zelf waar je ook je page kan testen op performance en toegankelijkheid

### performance

heb de live versie van de detailspage getest en zowel op mobile als desktop kwam er 100% uit dus qua performance is er niks nodig

<img src="https://github.com/user-attachments/assets/26687b2d-4b11-453e-ab5f-bab0122e04a5" width="400px" height="400px">
<img src="https://github.com/user-attachments/assets/4143b082-b69b-49a0-8f5e-7d050cd6e703" width="400px" height="400px">

### toegankelijkheid

Ik heb alleen hier de acces results van mobile sinds desktop dezelfde melding geeft. Alleen mobile heeft nog een extra melding

1. kleuren contrast verschil is te klein bij buttons 
2. checkbox tik ruimte en detail tik ruimte is te klein
3. label om checkbox heen. en aria label voor checkbox 
<img src="https://github.com/user-attachments/assets/0d0c81c3-235f-4084-a205-0ab4e5d3deab" width="400px" height="400px">

### feed back verwerken
1. contrast word al gefixed door een team genoot, omdat zei er ook dit kregen
2. de checkbox heeft geen tekst dus heb het een `aria-label` gegeven voor screen readers
```html
<label>
     <input type="checkbox" aria-label="fixed indicator" />
 </label>
```
3. heb de checkbox een min width en height gegeven zodat ze niet kleiner worden met wat ze nu zijn
 ```css
details summary input[type="checkbox"] {
    min-height: 25px;
    min-width: 25px;
    border: solid 2px var(--color-primary);
    position: relative;
    appearance: none;
    border-radius: 5px;
  }
```
