### ISSUE TITLE
Het maken van de deeltaak `scroll-driven-animation`

### ISSUE THREAD

**Issue by J3SS3HVA** [SamaraFellaDina/future-ready-design#79]
# Start maken

Eerst heb ik de deeltaak doorgenomen om te kijken wat de bedoeling is: [Deeltaak instructies](https://github.com/fdnd-task/user-needs/blob/main/docs/creative-coding-spike.md)

**Comment by J3SS3HVA** [comment]
# Schetsen

Heb ons orginele ontwerp gepakten hem een beetje redesigned

![ontwerp sprint 17](https://github.com/user-attachments/assets/5f99a1d1-15b9-4d63-82ab-313d7e17af6a)

## kenmerken

### Heb hiervoor een nieuwe kleuren palette

![colorpallette](https://github.com/user-attachments/assets/3bc65445-c3fa-4e76-99ce-d8cf6cff1220)

###

De ringen om het planeet gaan draaien wanneer het beelt scrolled

hoogs waarschijnlijk word dat dit binnen de keyframes

```css
 from {
    transform: rotate3d(360deg);
  }
```

**Comment by J3SS3HVA** [comment]
# 1ste versie

In de molecules folder heb ik nu een nieuw component die gelinked is in de `Layout.svelte` genaamt `Orbit.svelte`

## html

Ik heb een container met daarin 2 divjes die ringen om een planeet moeten voorstellen. Daarbij heb ik ook een div die het planeet zelf is

```html
<div class="spinner-box">
    <div class="big-orbit leo"> 
      <!-- <img src="https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fi.pinimg.com%2Foriginals%2Faf%2F52%2F70%2Faf52702337310d821f08dc8db63c9851.jpg&f=1&nofb=1&ipt=d1068ffb316b83af17defafe02e9cc301d30a5f08a5fa93da452d77189b3e95b&ipo=images" alt=""> -->
    </div>
    <div class="big-orbit2 leo2">
    </div>
    <div class="planet leo">
      <Wave />
      <div class="water-wave"></div>
    </div>
  </div>
```

## css

heb voor de ringen een animation dat ze rotaten in 3d en voor de planet dat de background beweegt alsof het lijkt dat hij echt draait. Naast dat heb ik ook met de `@support` gewerkt voor de scroll. als de browser dat support voert hij de animatie uit wanneer je scrolled. Als dat niet support heb ik als fallback dat hij constant bezig is met de animatie

```css
.big-orbit {
	width: 155px;
	height: 155px;
  border: 3px solid var(--color-blue);
  animation: spin3D 3s linear .2s infinite;
  rotate: 200deg;
}

.big-orbit2 {
	width: 145px;
	height: 145px;
  border: 3px solid var(--color-blue);
  animation: spin3D 3s linear .2s infinite;
  rotate: 200deg;
}

.planet{
  background-color: var(--color-status-fine-border);
  width: 100px;
  height: 100px;
  animation: unset;
  overflow-y: hidden;
  border: 2px solid indigo;
  
}

.planet::before {
  content: '';
  position: absolute;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
  background: linear-gradient(
    45deg,
    var(--color-blue),
    var(--color-lightblue),
    var(--color-blue),
    var(--color-lightblue),
    var(--color-blue),
    var(--color-lightblue),
    var(--color-blue),
    var(--color-lightblue)
  );
  background-size: 400%;
  /*opacity: 0;*/
  transition: 0.5s;
  animation: animate 20s linear infinite;
  z-index: -1;
  border-radius: 50%;
}

.planet::after {
  content: '';
  position: absolute;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
  background: linear-gradient(
    45deg,
    var(--color-blue),
    var(--color-lightblue),
    var(--color-blue),
    var(--color-lightblue),
    var(--color-blue),
    var(--color-lightblue),
    var(--color-blue),
    var(--color-lightblue)
  );
  background-size: 400%;
  /*opacity: 0;*/
  filter: blur(20px);
  transition: 0.5s;
  animation: animate 20s linear infinite;
  z-index: -1;
  border-radius: 50%;
}

.water-wave{
  background-color: indigo;
  height: 50%;
  width: 100%;
  position: absolute;
  top: 53%;
  border-radius: 0 0 50% 50%;
}


@supports (animation-timeline: scroll(y)) {
 
  .big-orbit, .big-orbit2 {
    animation: spin3D linear;
    animation-timeline: scroll(y); 
  }

  .planet::before, .planet::after{
    animation: animate linear;
    animation-timeline: scroll(y); 
  }
}

@keyframes spin3D {
  from {
    transform: rotate3d(.5,.5,.5, 360deg);
  }
  to{
    transform: rotate3d(0deg);
  }
}

@keyframes animate
{
	0%
	{
		background-position: 0 0;
	}
	50%
	{
		background-position: 300% 0;
	}
	100%
	{
		background-position: 0 0;
	}
}
```

## wave en resultaat

in de html is het je mischien opgevallen dat ik ook een wave component heb gelinked vanuit de atoms folder. Daar ben ik ook een beetje bezig geweest maar die krijgt grote veranderingen
