### ISSUE TITLE
versie 2 `scroll-driven-animation`

### ISSUE THREAD

**Issue by J3SS3HVA** [SamaraFellaDina/future-ready-design#82]
# ontwerpen van de 2de versie

[figma omgeving](https://www.figma.com/design/7MRqNISwfDsh8aolpEaTjl/FDND-opdracht-AccessDash-Scan-Results?node-id=623-52&node-type=canvas&t=MdPGn251lKTDwL47-0)

Ik ha dus een wave svg gevonden waarmee ik een soort van Ocean kan creëren. https://codepen.io/voskaul/pen/PWPpja

wat ik dus nu wil is dat het lijkt alsof de planeet op het water drijft

![ver2](https://github.com/user-attachments/assets/bfbede79-c7b9-4b3a-ba37-fd872fd275d6)

**Comment by J3SS3HVA** [comment]
# code updaten

ik heb de positie van waar de wave component staat dit keer buiten het divje van het planeet gezet.

`Orbit.svelte`

```html
<div class="spinner-box">
    <div class="big-orbit leo"> 
      <!-- <img src="https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fi.pinimg.com%2Foriginals%2Faf%2F52%2F70%2Faf52702337310d821f08dc8db63c9851.jpg&f=1&nofb=1&ipt=d1068ffb316b83af17defafe02e9cc301d30a5f08a5fa93da452d77189b3e95b&ipo=images" alt=""> -->
    </div>
    <div class="big-orbit2 leo2">
    </div>
    <div class="planet leo">
    </div>
    <Wave />
  </div>
```

Als extra heb ik de planet een  animation gegeven waardoor het lijkt dat hij drijft op het water

```css
@keyframes float {
  0% {
    transform: translateY(0px);
  }
  50%{
    transform: translateY(10px);
  }
  100%{
    transform: translateY(0px);
  }
}
```

`Wave.svelte`

Heb hier nu een nieuw divje die ervoor zorgt dat onder de wave een extra blokje krijgt, zodat het meer op een oceaan lijkt

```html
<div class="wave-container">
<svg viewBox="0 0 290 30">
  <path
    class="wave"
    fill="indigo"
    stroke="indigo"
    stroke-width="3"
    stroke-linecap="round"
    d="M0.100 25 c38 0 45-20 75-20s50 20 75 20 c38 0 45-5 75-20s50 20 75 20 c38 0 45-20 75-20s50 20 75 20 c38  0 45-20 75-20s50 20 75 20">
  </path>
</svg>

<div class="water-wave"></div>
</div>
```

**Comment by J3SS3HVA** [comment]
# resultaat


https://github.com/user-attachments/assets/41e04171-70d9-4f96-8802-cf0ea206f23f

**Comment by J3SS3HVA** [comment]
# section animations

heb ook alle sections een fadein animation gegeven. het enige verschil is dat sommige elementen van verschillende kanten tevoorschijn komen.

_belangrijke kenmerk_: elke section heeft dus ongeveer dezelfde animation. alleen hebben ze allemaal een animation delay van 2s extra

Alleen `Accessibillity.svelte` heeft de @support sinds die section buiten het scherm is.

```css
  section {
    background-color: var(--color-background-section);
    border-radius: var(--section-border-radius);
    box-shadow: var(--box-shadow);
    padding: var(--average-padding);
    grid-area: 4 / 1 / 5 / 3;
    animation: fadein 2s forwards;
    animation-delay: 6s;
    opacity: 0;
  }

  @supports (animation-timeline: scroll(y)) {
 
 section {
   animation: fadein linear;
   animation-timeline: scroll(y); 
 }
}
```

## ErrorResult.svelte `li` elementen

voor de `li` in `ErrorResult.svelte` heb ik een extra script gemaakt die steeds per `li` nog een animation delay van 0.2s erbij komt.
Dit maakt de fade in ook een stuk mooier
