### ISSUE TITLE
Het maken van de Deeltaak `view-transition api`

### ISSUE THREAD

**Issue by J3SS3HVA** [SamaraFellaDina/future-ready-design#85]
# wat is view-transitions

Je kan view transition gebruiken voor overgangen tussen elementen maar ook als je van de enige pagina naar de andere pagina gaat.

## overgaan naar andere pagina's

met dit kleine stukje css code kan je met een smooth transition van de ene pagina naar de andere pagina gaan
```css
@view-transition {
  navigation: auto;
}
```

## transitions in elementen
```html
<button id=b>Klik me</button>

<div id=d>
  <p>Hallo FDND!</p>
</div>
```

```css
div {
  width: 200px;
  aspect-ratio: 1;
  background: hotpink;
  display: grid;
  place-content: center;
  color: #fff;
  view-transition-name: super;
  p {
    display: none;
  }
}

div.active {
  background: rebeccapurple;
  width: 100px;
  margin-left: 50%;
  rotate: 405deg;
  p {
    display: block;
  }
}
```

```javascript
b.addEventListener('click', function() {
  if (document.startViewTransition){
    document.startViewTransition(toggleActiveState)
  } else {
    toggleActiveState()
  }
})

function toggleActiveState() {
  d.classList.toggle('active')
}
```

```css
::view-transition-group(super){
 anmation-duration: 3s;
}
```
