### ISSUE TITLE
bouwen van de deeltaak `audio api`

### ISSUE THREAD

**Issue by J3SS3HVA** [SamaraFellaDina/future-ready-design#97]
# inspiratie 

heb op code pen vallende sneeuw gevonde en wilde die graag meenemen naar mijn [sneeuw.](https://codepen.io/alphardex/pen/dyPorwJ) Het enige probleem waar ik tegen aanliep is dat het scss language is.

### scss werkend krijgen

1. npm i -D sass svelte-preprocess

2. in `svelte.config.js`

```javascript
import adapter from '@sveltejs/adapter-auto';
import sveltePreprocess from 'svelte-preprocess';

/** @type {import('@sveltejs/kit').Config} */
const config = {
  kit: {
    adapter: adapter(),
  },
  preprocess: sveltePreprocess({
    scss: {
      // optional: define global styles or variables
      additionalData: `@import './src/styles/variables.scss';`
    }
  })
};

export default config;
```

3. 
```css 
 <style lang="scss">
 ```

**Comment by J3SS3HVA** [comment]
## wat heb ik gemaakt

### html

hier is een voorbeeld. Elke section bevat 2 images van de verpakking. bij de ene is de linker half weg en bij de ander de rechter half. Met dit kan ik ervoor zorgen dat de uitpak animatie veel makkelijker gaat.

```html
<section id="a">
  <img src="https://i5.walmartimages.com/seo/Winter-Snowflakes-on-Blue-Premium-Roll-Gift-Wrap-Wrapping-Paper_0eb47d19-57cc-4f0e-84ff-3d582fbd5f59_1.a26f81b1f796b5b5d00cf447837cdd18.jpeg" class="inpak left-half" alt="">
  <img src="https://i5.walmartimages.com/seo/Winter-Snowflakes-on-Blue-Premium-Roll-Gift-Wrap-Wrapping-Paper_0eb47d19-57cc-4f0e-84ff-3d582fbd5f59_1.a26f81b1f796b5b5d00cf447837cdd18.jpeg" class="inpak right-half" alt="">
  <img src="https://img.pikbest.com/png-images/20241116/red-gift-bow-with-ribbon-detail-png-on-transparent-background_11096262.png!sw800"  width="200" height="200" class="strikje" alt="">
  <div>
    <h2>{result.title}</h2>
    <p>{result.description}</p>
  </div>
    <DonutChart {result}/>
</section>
```

### css

hier is hoe het bij elke section de css eruit ziet.
om het kort uit teleggen heb ik de section een animation gegeven dat hij gaat trillen, de animation duurt 1.2 seconden en wanneer hij voorbij is begint de animation van het uitpakken die bij de 2 images waar ik het over had.

```css
:global(section.section-tril) {
  animation: trillen 0.3s ease-in-out 4;
  cursor: unset;
}

  .inpak{
    position: absolute;
    width: 100%;
    height: 100%;
    left: 0;
    right: 0;
    bottom: 0;
    object-fit: cover;
    pointer-events: none;
    z-index: 1;
  }

  .right-half{
    clip-path: polygon(49% 0, 100% 0%, 100% 100%, 49% 100%);
    /* border-radius: var(--section-border-radius); */
  }

  :global(.right-half.uitpakken2){
    animation: naar-rechts 1s forwards;
    animation-delay: 1.2s;
  }

  .left-half{
    clip-path: polygon(50% 0, 0 0, 0 100%, 50% 100%);
    /* border-radius: var(--section-border-radius); */
  }

  :global(.left-half.uitpakken){
    animation: naar-links 1s forwards;
    animation-delay: 1.2s;
  }

  .strikje{
    position: absolute;
    top: 0%;
    left: 50%; 
    transform: translate(-50%, -50%); 
    z-index: 2;
  }

  h2 {
    margin-bottom: 50px;
    font-size: 2em;
  }

  @keyframes naar-links{
    to{
      transform: translateX(-500px);
      opacity: 0;
      display: none;
    }
  }

  @keyframes naar-rechts{
    to{
      transform: translateX(500px);
      opacity: 0;
      display: none;
    }
  }

  @keyframes trillen {
    0% {
      transform: translateX(0) rotate(0deg);
    }
    25% {
      transform: translateX(-5px) rotate(-2deg);
    }
    50% {
      transform: translateX(5px) rotate(2deg);
    }
    75% {
      transform: translateX(-5px) rotate(-2deg);
    }
    100% {
      transform: translateX(0) rotate(0deg);
    }
  }
```

**Comment by J3SS3HVA** [comment]
## uitzondering ErrorResult.svelte

Hier heb ik ervoor gezord dat elke individuele li diezelfde sounds en animation krijgt met ` Array.prototype.forEach.call(errorList, function (element) {`

```javascript
onMount(() => {
  const errorList = document.getElementsByClassName('liedjes');

  Array.prototype.forEach.call(errorList, function (element) {
    let clickCount = 0;

    element.addEventListener('click', () => {
      clickCount++; 

      if (clickCount % 2 !== 0) {
        
        setTimeout(() => {
          const audio = new Audio('./assets/sounds/papel-38926.mp3');
          audio.playbackRate = Math.max(6, audio.playbackRate - 6);
          audio.play();
        }, 0);

        setTimeout(() => {
          const audio2 = new Audio('./assets/sounds/bell.mp3');
          audio2.playbackRate = Math.max(1, audio2.playbackRate - 1);
          audio2.play();
        }, 1200);
      }
      
      const left = element.querySelector('.left-half-err');
      const right = element.querySelector('.right-half-err');

      left.classList.toggle('uitpakken-err');
      right.classList.toggle('uitpakken2-err');
      element.classList.toggle('li-tril');
    });
  });
});
```

**Comment by J3SS3HVA** [comment]
### Scss code

Ik had dus een vallende sneeuw animation gevonden en heb die verwerkt in mijn project als body background hier is hoe het werkt

1. setup: het maken vaan random gegenereerde nummers met de `random()` functie. 
2. Met `$min & $max` zorg ik uiteindelijk voor dat er wel een limit word ingesteld voor het random getal wat gegenereerd word
3. uiteindelijk zorg ik ervoor dat alle proporties die elke individuele div ook random zijn. Daarbij krijgen ze ook allemaal een apparte minimale en maximale waarde die ze kunnen krijgen
4. dat word  `&:nth-child(#{$i}) {` hier uiteindelijk aan ze gegeven. en ook aan de animations ,zodat elke div dus een aparte waarde krijgt bij het uitvoeren van de animatie 

```scss
 @function random_range($min, $max) {
      $rand: random();
      $random_range: $min + floor($rand * (($max - $min) + 1));
      @return $random_range;
    }
    
    .snow {
      $total: 200;
      position: fixed;
      width: 10px;
      left: 0;
      height: 10px;
      background: rgba(255, 255, 255, 0);
      border-radius: 50%;
      pointer-events:none;
    
      @for $i from 1 through $total {
        $random-x: random(1000000) * 0.0001vw;
        $random-offset: random_range(-100000, 100000) * 0.0001vw;
        $random-x-end: $random-x + $random-offset;
        $random-x-end-yoyo: $random-x + ($random-offset / 2);
        $random-yoyo-time: random_range(30000, 80000) / 100000;
        $random-yoyo-y: $random-yoyo-time * 100vh;
        $random-scale: random(10000) * 0.0001;
        $fall-duration: random_range(10, 30) * 1s;
        $fall-delay: random(30) * -1s;
    
        &:nth-child(#{$i}) {
          opacity: random(10000) * 0.0001;
          transform: translate($random-x, -10px) scale($random-scale);
          animation: fall-#{$i} $fall-duration $fall-delay linear infinite;
        }
    
        @keyframes fall-#{$i} {
          #{percentage($random-yoyo-time)} {
            transform: translate($random-x-end, $random-yoyo-y) scale($random-scale);
          }
    
          to {
            transform: translate($random-x-end-yoyo, 100vh) scale($random-scale);
          }
        }
      }
    } 

    @media screen and (max-width: 700px) {
      .snow{
        $total: 10;
      }
    }
```
